namespace Oscillite.CleanRoom.LSM
{
    public enum TraceProbeType
    {
        TRACE_PROBE_VOLTS,
        TRACE_PROBE_MIXTURE_CONTROL_DWELL_60,
        TRACE_PROBE_MIXTURE_CONTROL_DWELL_90,
        TRACE_PROBE_INJECTOR_PULSE_WIDTH,
        TRACE_PROBE_PULSE_WIDTH,
        TRACE_PROBE_DUTY_CYCLE,
        TRACE_PROBE_FREQUENCY,
        TRACE_PROBE_VOLTS_AC,
        TRACE_PROBE_VOLTS_DC,
        TRACE_PROBE_VACUUM_100,
        TRACE_PROBE_PRESSURE_100,
        TRACE_PROBE_PRESSURE_500,
        TRACE_PROBE_PRESSURE_5000,
        TRACE_PROBE_LOW_AMPS_20,
        TRACE_PROBE_LOW_AMPS_40,
        TRACE_PROBE_LOW_AMPS_60,
        TRACE_PROBE_IGNITION,
        TRACE_PROBE_OHMS,
        TRACE_PROBE_DIODE,
        TRACE_PROBE_SHUNT,
        TRACE_PROBE_USER_DEFINED,
        TRACE_PROBE_CAPACITANCE,
        TRACE_PROBE_EEDM506D_TEMPERATURE,
        TRACE_PROBE_MT5030_PRESSURE,
        TRACE_PROBE_MT5030_VACUUM,
        TRACE_PROBE_HIGH_AMPS_200,
        TRACE_PROBE_HIGH_AMPS_2000,
    }

}
